#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        if ! getent group hddtemp-exporter >/dev/null; then
            addgroup --quiet --system hddtemp-exporter
        fi

        if ! getent group node-exp >/dev/null; then
            addgroup --quiet --system node-exp
        fi

        if ! getent passwd hddtemp-exporter >/dev/null; then
            adduser --quiet --system --ingroup hddtemp-exporter --shell /usr/sbin/nologin hddtemp-exporter
            adduser hddtemp-exporter node-exp
        fi

        systemctl daemon-reload
        systemctl enable --now hddtemp-exporter.timer
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
